openapi: 3.1.0
info:
  title: OCA Repository
  description: 'This is official API specification of OCA Repository which you can read more about at [https://oca.colossi.network/ecosystem/oca-repository.html](https://oca.colossi.network/ecosystem/oca-repository.html)'
  version: 2.0.0
  contact:
    email: contact@humancolossus.org
servers:
  - url: https://repository.oca.argo.colossi.network/api/v2/
  - url: http://localhost:8000
tags:
  - name: OCA Bundle
    description: Endpoints to manage the OCA Bundles


paths:
  /oca-bundles:
    post:
      tags: [OCA Bundle]
      summary: Creates an OCA Bundle from OCAfile
      requestBody:
        content:
          text/plain:
            schema:
              type: string
            example: |-
              ADD ATTRIBUTE dateOfBirth=DateTime \
               documentNumber=Text \
                              documentType=[ Text ] fullName=Text \
                              height=Numeric issuingState=Text photoImage=Binary \
                              sex=Text ocrTextLines=[[ Text ]]

              ADD OVERLAY character_encoding
                attribute_character_encodings
                  photoImage="base64"

              ADD OVERLAY format
                attribute_formats
                  dateOfBirth="YYYY-MM-DD"
                  documentNumber="[A-Z0-9]{9}"
                  photoImage="image/jpeg"
                  sex="[A-Z]{1}"

              ADD OVERLAY label
                language="en"
                attribute_labels
                  dateOfBirth="Date of birth"
                  documentNumber="Passport Number"
                  documentType="Document"
                  fullName="Name"
                  height="Height"
                  issuingState="Issuing State or organization (in full)"
                  photoImage="Portrait image"
                  sex="Sex"

              ADD Overlay meta
                language="en"
                name="Digital Passport"
                description="An example of a Digital Passport schema"
                affiliation="The Goverment of Antarctica"

              ADD Overlay standard
                attribute_standards
                  dateOfBirth="ISO 8601"
                  documentNumber="ISO 3166-1 alpha-2"

              ADD Overlay cardinality
                attribute_cardinalities
                  documentType="1-2"

              ADD Overlay conformance
                attribute_conformances
                  documentType="M"
                  fullName="M"
                  height="optional"
                  issuingState="O"
                  photoImage="M"
                  sex="M"

              ADD Overlay entry_code
                attribute_entry_codes
                  documentType=["PE", "PM"]
                  issuingState=refs:EGyWgdQR9dW_I5oHlHBMoO9AA_eMeb2p3XzcCRCBbKCM
                  sex=["F", "M", "X"]

              ADD Overlay entry
                language="en"
                attribute_entries
                  issuingState=refs:EGyWgdQR9dW_I5oHlHBMoO9AA_eMeb2p3XzcCRCBbKCM
                  documentType
                    PE="Diplomatic Passport"
                    PM="Passport"
                  sex
                    F="Female"
                    M="Male"
                    X="Unspecified"

              ADD Overlay UNIT
                metric_system="SI"
                attribute_units
                  height="cm"

              ADD Overlay mapping
                attribute_mappings
                  dateOfBirth="birth_date"
                  documentNumber="document_number"
                  documentType="document_type"
                  fullName="name"
                  height="person_height"
                  issuingState="issuing_state"

              ADD Overlay entry_code_mapping
                attribute_entry_codes_mappings
                  documentType=["PE:KE", "PM:ZK" ]

              ADD overlay sensitive
                attributes=["fullName", "photoImage", "dataOfBirth", "documentNumber"]
      responses:
        '200':
          description: OCA Bundle created successfully
          content:
            application/json:
              schema:
                type: object
                items:
                  type: object
                  properties:
                    success:
                      type: boolean
                    said:
                      type: string

  /oca-bundles/{said}:
    get:
      tags: [OCA Bundle]
      summary: Get OCA Bundle
      parameters:
        - name: said
          in: path
          required: true
          description: OCA Bundle SAID
          schema:
            type: string
        - name: w
          in: query
          description: With dependecies - dereference all nested SAID and provide in form of an array
          schema:
            type: boolean
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BundleWithDeps'
        '404':
          description: Bundle not found

  /oca-bundles/{said}/steps:
    get:
      tags: [OCA Bundle]
      summary: List OCAFile steps which where used to build OCA Bundle
      parameters:
        - name: said
          in: path
          required: true
          description: OCA Bundle SAID
          schema:
            type: string
        - name: extend
          in: query
          description: Extend steps by resulted OCA Bundle
          schema:
            type: boolean
      responses:
        '200':
          description: Successful response
        '404':
          description: Bundle not found

  /oca-bundles/{said}/ocafile:
    get:
      tags: [OCA Bundle]
      summary: Recreate OCAFILE from OCA Bundle
      parameters:
        - name: said
          in: path
          required: true
          description: OCA Bundle SAID
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '404':
          description: Bundle not found

  /oca-bundles/{said}/data-entry:
    get:
      tags: [OCA Bundle]
      summary: Download OCA Bundle data entry file (CSV or XLSX)
      parameters:
        - name: said
          in: path
          required: true
          description: OCA Bundle SAID
          schema:
            type: string
        - name: format
          in: query
          description: Output format (csv or xlsx). Default is xlsx.
          schema:
            type: string
        - name: labels
          in: query
          description: Language code for labels (e.g., en).
          schema:
            type: string
        - name: metadata
          in: query
          description: Language code for metadata (e.g., en).
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '404':
          description: Bundle not found

  /explore/{said}:
    get:
      tags: [OCA Bundle]
      summary: Get relations of any OCA object
      parameters:
        - name: said
          in: path
          required: true
          description: OCA object SAID
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '404':
          description: Bundle not found

  /objects:
    get:
      tags: [OCA Bundle]
      summary: Get list of OCA objects
      parameters:
        - name: said
          in: query
          required: true
          description: List of OCA object SAIDs separated by comma
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '404':
          description: Bundle not found

components:
  securitySchemes:
    namespaceToken:
      type: http
      scheme: bearer
  schemas:
    BundleWithDeps:
      type: object
      properties:
        bundles:
          type: object
          description: Main oca bundle
        dependencies:
          type: array
          items:
            type: object
            description: oca bundle
